src/Entity/Creature.php
<?php

namespace App\Entity;

use App\Repository\CreatureRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CreatureRepository::class)]
class Creature
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_creature;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description_creature;

    #[ORM\Column(type: 'string', length: 255)]
    private $habitat_creature;

    #[ORM\Column(type: 'string', length: 255)]
    private $regime_creature;

    #[ORM\ManyToOne(targetEntity: Race::class, inversedBy: 'creatures')]
    private $race;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCreature(): ?string
    {
        return $this->nom_creature;
    }

    public function setNomCreature(string $nom_creature): self
    {
        $this->nom_creature = $nom_creature;

        return $this;
    }

    public function getDescriptionCreature(): ?string
    {
        return $this->description_creature;
    }

    public function setDescriptionCreature(?string $description_creature): self
    {
        $this->description_creature = $description_creature;

        return $this;
    }

    public function getHabitatCreature(): ?string
    {
        return $this->habitat_creature;
    }

    public function setHabitatCreature(string $habitat_creature): self
    {
        $this->habitat_creature = $habitat_creature;

        return $this;
    }

    public function getRegimeCreature(): ?string
    {
        return $this->regime_creature;
    }

    public function setRegimeCreature(string $regime_creature): self
    {
        $this->regime_creature = $regime_creature;

        return $this;
    }

    public function getRace(): ?race
    {
        return $this->race;
    }

    public function setRace(?race $race): self
    {
        $this->race = $race;

        return $this;
    }
}

src/Form/CreatureType.php
<?php

namespace App\Form;

use App\Entity\Creature;
use App\Entity\Race;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class CreatureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_creature')
            ->add('description_creature')
            ->add('habitat_creature', ChoiceType::class, [
                'choices' => [
                    'Plaine' => 'Plaine',
                    'Montagne' => 'Montagne',
                    'Souterrains' => 'Souterrains',
                    'Zone Enneigés' => 'Zone Enneigés',
                    'Forêt' => 'Forêt'
                ]
            ])
            ->add('regime_creature', ChoiceType::class, [
                'choices'  => [
                    'Omnivore' => 'Omnivore',
                    'Herbivore' =>'Herbivore',
                    'Carnivore' => "Carnivore",
                    'Cristovore' => "Cristovore"
                ]
            ])
            ->add('race', EntityType::class,[
                'class' => Race::class,
                'choice_label' => 'nom_race',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Creature::class,
        ]);
    }
}

src/Controller/CreatureController.php
<?php

namespace App\Controller;

use App\Entity\Creature;
use App\Form\CreatureType;
use App\Repository\CreatureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/creature')]
class CreatureController extends AbstractController
{
    #[Route('/', name: 'app_creature_index', methods: ['GET'])]
    public function index(CreatureRepository $creatureRepository): Response
    {
        return $this->render('creature/index.html.twig', [
            'creatures' => $creatureRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_creature_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CreatureRepository $creatureRepository): Response
    {
        $creature = new Creature();
        $form = $this->createForm(CreatureType::class, $creature);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $creatureRepository->add($creature);
            return $this->redirectToRoute('app_creature_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('creature/new.html.twig', [
            'creature' => $creature,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_creature_show', methods: ['GET'])]
    public function show(Creature $creature): Response
    {
        return $this->render('creature/show.html.twig', [
            'creature' => $creature,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_creature_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Creature $creature, CreatureRepository $creatureRepository): Response
    {
        $form = $this->createForm(CreatureType::class, $creature);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $creatureRepository->add($creature);
            return $this->redirectToRoute('app_creature_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('creature/edit.html.twig', [
            'creature' => $creature,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_creature_delete', methods: ['POST'])]
    public function delete(Request $request, Creature $creature, CreatureRepository $creatureRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$creature->getId(), $request->request->get('_token'))) {
            $creatureRepository->remove($creature);
        }

        return $this->redirectToRoute('app_creature_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/creature/_delete_form.html.twig
<form method="post" action="{{ path('app_creature_delete', {'id': creature.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ creature.id) }}">
    <button class="btn">Delete</button>
</form>

templates/creature/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Creature{% endblock %}

{% block body %}
    <h1>Edit Creature</h1>

    {{ include('creature/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_creature_index') }}">back to list</a>

    {{ include('creature/_delete_form.html.twig') }}
{% endblock %}

templates/creature/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creature index{% endblock %}

{% block body %}
    <h1>Creature index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_creature</th>
                <th>Description_creature</th>
                <th>Habitat_creature</th>
                <th>Regime_creature</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for creature in creatures %}
            <tr>
                <td>{{ creature.id }}</td>
                <td>{{ creature.nomCreature }}</td>
                <td>{{ creature.descriptionCreature }}</td>
                <td>{{ creature.habitatCreature }}</td>
                <td>{{ creature.regimeCreature }}</td>
                <td>
                    <a href="{{ path('app_creature_show', {'id': creature.id}) }}">show</a>
                    <a href="{{ path('app_creature_edit', {'id': creature.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_creature_new') }}">Create new</a>
{% endblock %}

templates/creature/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Creature{% endblock %}

{% block body %}
    <h1>Create new Creature</h1>

    {{ include('creature/_form.html.twig') }}

    <a href="{{ path('app_creature_index') }}">back to list</a>
{% endblock %}

templates/creature/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creature{% endblock %}

{% block body %}
    <h1>Creature</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ creature.id }}</td>
            </tr>
            <tr>
                <th>Nom_creature</th>
                <td>{{ creature.nomCreature }}</td>
            </tr>
            <tr>
                <th>Description_creature</th>
                <td>{{ creature.descriptionCreature }}</td>
            </tr>
            <tr>
                <th>Habitat_creature</th>
                <td>{{ creature.habitatCreature }}</td>
            </tr>
            <tr>
                <th>Regime_creature</th>
                <td>{{ creature.regimeCreature }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_creature_index') }}">back to list</a>

    <a href="{{ path('app_creature_edit', {'id': creature.id}) }}">edit</a>

    {{ include('creature/_delete_form.html.twig') }}
{% endblock %}