src/Entity/FichePersonnage.php
<?php

namespace App\Entity;

use App\Repository\FichePersonnageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: FichePersonnageRepository::class)]
class FichePersonnage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'integer')]
    private $age;

    #[ORM\Column(type: 'integer')]
    private $taille;

    #[ORM\Column(type: 'integer')]
    private $poids;

    #[ORM\Column(type: 'string', length: 255)]
    private $yeux;

    #[ORM\Column(type: 'string', length: 255)]
    private $cheveux;

    /**
     * @Assert\Range(
     *      min = 1,
     *      max = 10,
     *      notInRangeMessage = "La valeur doit être entre 1 et 10",
     * )
     */
    #[ORM\Column(type: 'integer')]
    private $constitution;

    /**
     * @Assert\Range(
     *      min = 1,
     *      max = 10,
     *      notInRangeMessage = "La valeur doit être entre 1 et 10",
     * )
     */
    #[ORM\Column(type: 'integer')]
    private $force_personnage;

    /**
     * @Assert\Range(
     *      min = 1,
     *      max = 10,
     *      notInRangeMessage = "La valeur doit être entre 1 et 10",
     * )
     */
    #[ORM\Column(type: 'integer')]
    private $perception;

    /**
     * @Assert\Range(
     *      min = 1,
     *      max = 10,
     *      notInRangeMessage = "La valeur doit être entre 1 et 10",
     * )
     */
    #[ORM\Column(type: 'integer')]
    private $intelligence;

    /**
     * @Assert\Range(
     *      min = 1,
     *      max = 10,
     *      notInRangeMessage = "La valeur doit être entre 1 et 10",
     * )
     */
    #[ORM\Column(type: 'integer')]
    private $sagesse;


    /**
     * @Assert\Range(
     *      min = 1,
     *      max = 10,
     *      notInRangeMessage = "La valeur doit être entre 1 et 10",
     * )
     */
    #[ORM\Column(type: 'integer')]
    private $charisme;

    /**
     * @Assert\Range(
     *      min = 1,
     *      max = 10,
     *      notInRangeMessage = "La valeur doit être entre 1 et 10",
     * )
     */
    #[ORM\Column(type: 'integer')]
    private $fuite;

    /**
     * @Assert\Range(
     *      min = 1,
     *      max = 10,
     *      notInRangeMessage = "La valeur doit être entre 1 et 10",
     * )
     */
    #[ORM\Column(type: 'integer')]
    private $dexterite;

    #[ORM\Column(type: 'string')]
    private $sexe;

    #[ORM\ManyToMany(targetEntity: Objet::class, inversedBy: 'fichePersonnages')]
    private $objets;

    #[ORM\ManyToOne(targetEntity: Classe::class, inversedBy: 'fichePersonnages')]
    private $classe;

    #[ORM\ManyToOne(targetEntity: Pays::class, inversedBy: 'fichePersonnages')]
    private $pays;

    #[ORM\ManyToOne(targetEntity: Ville::class, inversedBy: 'fichePersonnages')]
    private $ville;

    #[ORM\ManyToOne(targetEntity: Religion::class, inversedBy: 'fichePersonnages')]
    private $religion;

    #[ORM\ManyToOne(targetEntity: Race::class, inversedBy: 'fichePersonnages')]
    private $race;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class, inversedBy: 'fichePersonnages')]
    private $utilisateur;

    /**
     * @return mixed
     */
    public function getSagesse()
    {
        return $this->sagesse;
    }

    /**
     * @param mixed $sagesse
     */
    public function setSagesse($sagesse): void
    {
        $this->sagesse = $sagesse;
    }

    /**
     * @return mixed
     */
    public function getSexe()
    {
        return $this->sexe;
    }

    /**
     * @param mixed $sexe
     */
    public function setSexe($sexe): void
    {
        $this->sexe = $sexe;
    }

    public function __construct()
    {
        $this->objets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getTaille(): ?int
    {
        return $this->taille;
    }

    public function setTaille(int $taille): self
    {
        $this->taille = $taille;

        return $this;
    }

    public function getPoids(): ?int
    {
        return $this->poids;
    }

    public function setPoids(int $poids): self
    {
        $this->poids = $poids;

        return $this;
    }

    public function getYeux(): ?string
    {
        return $this->yeux;
    }

    public function setYeux(string $yeux): self
    {
        $this->yeux = $yeux;

        return $this;
    }

    public function getCheveux(): ?string
    {
        return $this->cheveux;
    }

    public function setCheveux(string $cheveux): self
    {
        $this->cheveux = $cheveux;

        return $this;
    }

    public function getConstitution(): ?int
    {
        return $this->constitution;
    }

    public function setConstitution(int $constitution): self
    {
        $this->constitution = $constitution;

        return $this;
    }

    public function getForcePersonnage(): ?int
    {
        return $this->force_personnage;
    }

    public function setForcePersonnage(int $force_personnage): self
    {
        $this->force_personnage = $force_personnage;

        return $this;
    }

    public function getPerception(): ?int
    {
        return $this->perception;
    }

    public function setPerception(int $perception): self
    {
        $this->perception = $perception;

        return $this;
    }

    public function getIntelligence(): ?int
    {
        return $this->intelligence;
    }

    public function setIntelligence(int $intelligence): self
    {
        $this->intelligence = $intelligence;

        return $this;
    }

    public function getCharisme(): ?int
    {
        return $this->charisme;
    }

    public function setCharisme(int $charisme): self
    {
        $this->charisme = $charisme;

        return $this;
    }

    public function getFuite(): ?int
    {
        return $this->fuite;
    }

    public function setFuite(int $fuite): self
    {
        $this->fuite = $fuite;

        return $this;
    }

    public function getDexterite(): ?int
    {
        return $this->dexterite;
    }

    public function setDexterite(int $dexterite): self
    {
        $this->dexterite = $dexterite;

        return $this;
    }

    /**
     * @return Collection<int, objet>
     */
    public function getObjets(): Collection
    {
        return $this->objets;
    }

    public function addObjet(objet $objet): self
    {
        if (!$this->objets->contains($objet)) {
            $this->objets[] = $objet;
        }

        return $this;
    }

    public function removeObjet(objet $objet): self
    {
        $this->objets->removeElement($objet);

        return $this;
    }

    public function getClasse(): ?classe
    {
        return $this->classe;
    }

    public function setClasse(?classe $classe): self
    {
        $this->classe = $classe;

        return $this;
    }

    public function getPays(): ?pays
    {
        return $this->pays;
    }

    public function setPays(?pays $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getVille(): ?ville
    {
        return $this->ville;
    }

    public function setVille(?ville $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getReligion(): ?religion
    {
        return $this->religion;
    }

    public function setReligion(?religion $religion): self
    {
        $this->religion = $religion;

        return $this;
    }

    public function getRace(): ?race
    {
        return $this->race;
    }

    public function setRace(?race $race): self
    {
        $this->race = $race;

        return $this;
    }

    public function getUtilisateur(): ?utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }
}

src/Form/FichePersonnageType.php
<?php

namespace App\Form;

use App\Entity\FichePersonnage;
use App\Entity\Objet;
use App\Entity\Pays;
use App\Entity\Religion;
use App\Entity\Utilisateur;
use App\Entity\Ville;
use App\Entity\Classe;
use App\Entity\Race;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FichePersonnageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
           ->add('age')
            ->add('taille')
            ->add('poids')
            ->add('yeux')
            ->add('cheveux')
            ->add('constitution')
            ->add('force_personnage')
            ->add('perception')
            ->add('intelligence')
            ->add('sagesse')
            ->add('charisme')
            ->add('fuite')
            ->add('dexterite')
            ->add('classe', EntityType::class, [
                'class' => Classe::class,
                'choice_label' => 'nom_classe'
            ])

            ->add('Ville', EntityType::class, [
                'class' => Ville::class,
                'choice_label' => 'nom_ville',
            ])

            ->add('religion',  EntityType::class, [
                'class' => Religion::class,
                'choice_label' => 'nom_religion',
            ])
            ->add('race', EntityType::class,[
                'class' => Race::class,
                'choice_label' => 'nom_race',
            ])
            ->add('pays', EntityType::class, [
                'class' => Pays::class,
                'choice_label' => 'nom_pays',
            ])
            ->add('sexe', ChoiceType::class, [
                'choices'  => [
                    'Homme' => "Homme",
                    'Femme' => "Femme",
                    'Non Spécifié' => "Non Spécifié",
                ]
            ])
            ->add('Valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => FichePersonnage::class,
        ]);
    }
}

src/Controller/FichePersonnageController.php
<?php

namespace App\Controller;

use App\Entity\FichePersonnage;
use App\Form\FichePersonnageType;
use App\Repository\FichePersonnageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/fiche/personnage')]
class FichePersonnageController extends AbstractController
{
    #[Route('/', name: 'app_fiche_personnage_index', methods: ['GET'])]
    public function index(FichePersonnageRepository $fichePersonnageRepository): Response
    {
        return $this->render('fiche_personnage/index.html.twig', [
            'fiche_personnages' => $fichePersonnageRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_fiche_personnage_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FichePersonnageRepository $fichePersonnageRepository): Response
    {
        $fichePersonnage = new FichePersonnage();
        $form = $this->createForm(FichePersonnageType::class, $fichePersonnage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $fichePersonnageRepository->add($fichePersonnage);
            return $this->redirectToRoute('app_fiche_personnage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fiche_personnage/new.html.twig', [
            'fiche_personnage' => $fichePersonnage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fiche_personnage_show', methods: ['GET'])]
    public function show(FichePersonnage $fichePersonnage): Response
    {
        return $this->render('fiche_personnage/show.html.twig', [
            'fiche_personnage' => $fichePersonnage,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_fiche_personnage_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, FichePersonnage $fichePersonnage, FichePersonnageRepository $fichePersonnageRepository): Response
    {
        $form = $this->createForm(FichePersonnageType::class, $fichePersonnage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $fichePersonnageRepository->add($fichePersonnage);
            return $this->redirectToRoute('app_fiche_personnage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fiche_personnage/edit.html.twig', [
            'fiche_personnage' => $fichePersonnage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fiche_personnage_delete', methods: ['POST'])]
    public function delete(Request $request, FichePersonnage $fichePersonnage, FichePersonnageRepository $fichePersonnageRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fichePersonnage->getId(), $request->request->get('_token'))) {
            $fichePersonnageRepository->remove($fichePersonnage);
        }

        return $this->redirectToRoute('app_fiche_personnage_index', [], Response::HTTP_SEE_OTHER);
    }


}

templates/fiche_personnage/_delete_form.html.twig
<form method="post" action="{{ path('app_fiche_personnage_delete', {'id': fiche_personnage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fiche_personnage.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fiche_personnage/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FichePersonnage{% endblock %}

{% block body %}
    <h1>Edit FichePersonnage</h1>

    {{ include('fiche_personnage/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_fiche_personnage_index') }}">back to list</a>

    {{ include('fiche_personnage/_delete_form.html.twig') }}
{% endblock %}

templates/fiche_personnage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FichePersonnage index{% endblock %}

{% block body %}
    <h1>FichePersonnage index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_personnage</th>
                <th>Prenom_personnage</th>
                <th>Age_personnage</th>
                <th>Taille_personnage</th>
                <th>Poids_personnage</th>
                <th>Yeux_personnage</th>
                <th>Cheveux_personnage</th>
                <th>Constitution_personnage</th>
                <th>Force_personnage</th>
                <th>Perception_personnage</th>
                <th>Intelligence_personnage</th>
                <th>Charisme_personnage</th>
                <th>Fuite_personnage</th>
                <th>Dexterite_personnage</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fiche_personnage in fiche_personnages %}
            <tr>
                <td>{{ fiche_personnage.id }}</td>
                <td>{{ fiche_personnage.nomPersonnage }}</td>
                <td>{{ fiche_personnage.prenomPersonnage }}</td>
                <td>{{ fiche_personnage.agePersonnage }}</td>
                <td>{{ fiche_personnage.taillePersonnage }}</td>
                <td>{{ fiche_personnage.poidsPersonnage }}</td>
                <td>{{ fiche_personnage.yeuxPersonnage }}</td>
                <td>{{ fiche_personnage.cheveuxPersonnage }}</td>
                <td>{{ fiche_personnage.constitutionPersonnage }}</td>
                <td>{{ fiche_personnage.forcePersonnage }}</td>
                <td>{{ fiche_personnage.perceptionPersonnage }}</td>
                <td>{{ fiche_personnage.intelligencePersonnage }}</td>
                <td>{{ fiche_personnage.charismePersonnage }}</td>
                <td>{{ fiche_personnage.fuitePersonnage }}</td>
                <td>{{ fiche_personnage.dexteritePersonnage }}</td>
                <td>
                    <a href="{{ path('app_fiche_personnage_show', {'id': fiche_personnage.id}) }}">show</a>
                    <a href="{{ path('app_fiche_personnage_edit', {'id': fiche_personnage.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="16">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_fiche_personnage_new') }}">Create new</a>
{% endblock %}

templates/fiche_personnage/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New FichePersonnage{% endblock %}

{% block body %}
    <h1>Create new FichePersonnage</h1>

    {{ include('fiche_personnage/_form.html.twig') }}

    <a href="{{ path('app_fiche_personnage_index') }}">back to list</a>
{% endblock %}

templates/fiche_personnage/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FichePersonnage{% endblock %}

{% block body %}
    <h1>FichePersonnage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fiche_personnage.id }}</td>
            </tr>
            <tr>
                <th>Nom_personnage</th>
                <td>{{ fiche_personnage.nomPersonnage }}</td>
            </tr>
            <tr>
                <th>Prenom_personnage</th>
                <td>{{ fiche_personnage.prenomPersonnage }}</td>
            </tr>
            <tr>
                <th>Age_personnage</th>
                <td>{{ fiche_personnage.agePersonnage }}</td>
            </tr>
            <tr>
                <th>Taille_personnage</th>
                <td>{{ fiche_personnage.taillePersonnage }}</td>
            </tr>
            <tr>
                <th>Poids_personnage</th>
                <td>{{ fiche_personnage.poidsPersonnage }}</td>
            </tr>
            <tr>
                <th>Yeux_personnage</th>
                <td>{{ fiche_personnage.yeuxPersonnage }}</td>
            </tr>
            <tr>
                <th>Cheveux_personnage</th>
                <td>{{ fiche_personnage.cheveuxPersonnage }}</td>
            </tr>
            <tr>
                <th>Constitution_personnage</th>
                <td>{{ fiche_personnage.constitutionPersonnage }}</td>
            </tr>
            <tr>
                <th>Force_personnage</th>
                <td>{{ fiche_personnage.forcePersonnage }}</td>
            </tr>
            <tr>
                <th>Perception_personnage</th>
                <td>{{ fiche_personnage.perceptionPersonnage }}</td>
            </tr>
            <tr>
                <th>Intelligence_personnage</th>
                <td>{{ fiche_personnage.intelligencePersonnage }}</td>
            </tr>
            <tr>
                <th>Charisme_personnage</th>
                <td>{{ fiche_personnage.charismePersonnage }}</td>
            </tr>
            <tr>
                <th>Fuite_personnage</th>
                <td>{{ fiche_personnage.fuitePersonnage }}</td>
            </tr>
            <tr>
                <th>Dexterite_personnage</th>
                <td>{{ fiche_personnage.dexteritePersonnage }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_fiche_personnage_index') }}">back to list</a>

    <a href="{{ path('app_fiche_personnage_edit', {'id': fiche_personnage.id}) }}">edit</a>

    {{ include('fiche_personnage/_delete_form.html.twig') }}
{% endblock %}