src/Entity/Campagne.php
<?php

namespace App\Entity;

use App\Repository\CampagneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CampagneRepository::class)]
class Campagne
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre_campagne;

    #[ORM\Column(type: 'text')]
    private $description_campagne;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class, inversedBy: 'campagne')]
    private $utilisateur;

    #[ORM\OneToMany(mappedBy: 'campagne', targetEntity: Theme::class)]
    private $themes;


    public function __construct()
    {
        $this->themes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreCampagne(): ?string
    {
        return $this->titre_campagne;
    }

    public function setTitreCampagne(string $titre_campagne): self
    {
        $this->titre_campagne = $titre_campagne;

        return $this;
    }

    public function getDescriptionCampagne(): ?string
    {
        return $this->description_campagne;
    }

    public function setDescriptionCampagne(string $description_campagne): self
    {
        $this->description_campagne = $description_campagne;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    /**
     * @return Collection<int, Theme>
     */
    public function getThemes(): Collection
    {
        return $this->themes;
    }

    public function addTheme(Theme $theme): self
    {
        if (!$this->themes->contains($theme)) {
            $this->themes[] = $theme;
            $theme->setCampagne($this);
        }

        return $this;
    }

    public function removeTheme(Theme $theme): self
    {
        if ($this->themes->removeElement($theme)) {
            // set the owning side to null (unless already changed)
            if ($theme->getCampagne() === $this) {
                $theme->setCampagne(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Theme>
     */
    public function getTheme(): Collection
    {
        return $this->theme;
    }
}

src/Form/CampagneType.php
<?php

namespace App\Form;

use App\Entity\Campagne;
use App\Entity\Utilisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CampagneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre_campagne')
            ->add('description_campagne')
            ->add('utilisateur', EntityType::class,[
                'class' => Utilisateur::class,
                'choice_label' => 'pseudo',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Campagne::class,
        ]);
    }
}

src/Controller/CampagneController.php
<?php

namespace App\Controller;

use App\Entity\Campagne;
use App\Form\CampagneType;
use App\Repository\CampagneRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/campagne')]
class CampagneController extends AbstractController
{
    #[Route('/', name: 'app_campagne_index', methods: ['GET'])]
    public function index(CampagneRepository $campagneRepository): Response
    {
        return $this->render('campagne/index.html.twig', [
            'campagnes' => $campagneRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_campagne_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CampagneRepository $campagneRepository): Response
    {
        $campagne = new Campagne();
        $form = $this->createForm(CampagneType::class, $campagne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campagneRepository->add($campagne);
            return $this->redirectToRoute('app_campagne_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('campagne/new.html.twig', [
            'campagne' => $campagne,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_campagne_show', methods: ['GET'])]
    public function show(Campagne $campagne): Response
    {
        return $this->render('campagne/show.html.twig', [
            'campagne' => $campagne,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_campagne_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Campagne $campagne, CampagneRepository $campagneRepository): Response
    {
        $form = $this->createForm(CampagneType::class, $campagne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campagneRepository->add($campagne);
            return $this->redirectToRoute('app_campagne_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('campagne/edit.html.twig', [
            'campagne' => $campagne,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_campagne_delete', methods: ['POST'])]
    public function delete(Request $request, Campagne $campagne, CampagneRepository $campagneRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$campagne->getId(), $request->request->get('_token'))) {
            $campagneRepository->remove($campagne);
        }

        return $this->redirectToRoute('app_campagne_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/campagne/_delete_form.html.twig
<form method="post" action="{{ path('app_campagne_delete', {'id': campagne.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ campagne.id) }}">
    <button class="btn">Delete</button>
</form>

templates/campagne/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Campagne{% endblock %}

{% block body %}
    <h1>Edit Campagne</h1>

    {{ include('campagne/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_campagne_index') }}">back to list</a>

    {{ include('campagne/_delete_form.html.twig') }}
{% endblock %}

templates/campagne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Campagne index{% endblock %}

{% block body %}
    <h1>Campagne index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre_campagne</th>
                <th>Description_campagne</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for campagne in campagnes %}
            <tr>
                <td>{{ campagne.id }}</td>
                <td>{{ campagne.titreCampagne }}</td>
                <td>{{ campagne.descriptionCampagne }}</td>
                <td>
                    <a href="{{ path('app_campagne_show', {'id': campagne.id}) }}">show</a>
                    <a href="{{ path('app_campagne_edit', {'id': campagne.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_campagne_new') }}">Create new</a>
{% endblock %}

templates/campagne/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Campagne{% endblock %}

{% block body %}
    <h1>Create new Campagne</h1>

    {{ include('campagne/_form.html.twig') }}

    <a href="{{ path('app_campagne_index') }}">back to list</a>
{% endblock %}

templates/campagne/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Campagne{% endblock %}

{% block body %}
    <h1>Campagne</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ campagne.id }}</td>
            </tr>
            <tr>
                <th>Titre_campagne</th>
                <td>{{ campagne.titreCampagne }}</td>
            </tr>
            <tr>
                <th>Description_campagne</th>
                <td>{{ campagne.descriptionCampagne }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_campagne_index') }}">back to list</a>

    <a href="{{ path('app_campagne_edit', {'id': campagne.id}) }}">edit</a>

    {{ include('campagne/_delete_form.html.twig') }}
{% endblock %}