src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $message;

    #[ORM\ManyToOne(targetEntity: Theme::class, inversedBy: 'messages')]
    private $theme;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class, inversedBy: 'messages')]
    private $utilisateur;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

public function __construct()
    {
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getTheme(): ?theme
    {
        return $this->theme;
    }

    public function setTheme(?theme $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getUtilisateur(): ?utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function __toString()
    {
        return "";
    }
}

src/Entity/Theme.php
<?php

namespace App\Entity;

use App\Repository\ThemeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Nullable;

#[ORM\Entity(repositoryClass: ThemeRepository::class)]
class Theme
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre_theme;

    #[ORM\Column(type: 'text')]
    private $description_theme;

    #[ORM\OneToMany(mappedBy: 'theme', targetEntity: Message::class)]
    private $messages;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class, inversedBy: 'themes')]
    private $utilisateur;

    #[ORM\ManyToOne(targetEntity: Campagne::class, inversedBy: 'themes')]
    private $campagne;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $photo;


    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreTheme(): ?string
    {
        return $this->titre_theme;
    }

    public function setTitreTheme(string $titre_theme): self
    {
        $this->titre_theme = $titre_theme;

        return $this;
    }

    public function getDescriptionTheme(): ?string
    {
        return $this->description_theme;
    }

    public function setDescriptionTheme(string $description_theme): self
    {
        $this->description_theme = $description_theme;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setTheme($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getTheme() === $this) {
                $message->setTheme(null);
            }
        }

        return $this;
    }

    public function getUtilisateur(): ?utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getCampagne(): ?campagne
    {
        return $this->campagne;
    }

    public function setCampagne(?campagne $campagne): self
    {
        $this->campagne = $campagne;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function __toString()
    {
        return "";
    }

}

src/Form/ThemeType.php
<?php

namespace App\Form;

use App\Entity\Campagne;
use App\Entity\Theme;
use App\Entity\Utilisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ThemeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre_theme', TextType::class, [
            ])
            ->add('description_theme')
            ->add('campagne', EntityType::class,[
                'class' => Campagne::class,
                'choice_label' => 'titre_campagne',
                'required'   => false,
            ])
            ->add('photo', FileType::class, [
                'label' => 'Photo de profil du theme (Format PNG, JPG, JPEG)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/jpg',
                        ],
                        'mimeTypesMessage' => 'Veuillez envoyer une image sous format JPG,JPEG ou PNG',
                    ])
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Theme::class,
        ]);
    }
}

src/Controller/ThemeController.php
<?php

namespace App\Controller;

use App\Entity\Theme;
use App\Form\ThemeType;
use App\Repository\MessageRepository;
use App\Repository\ThemeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use App\Entity\Message;
use App\Form\MessageType;
use App\Repository\UtilisateurRepository;

#[Route('/theme')]
class ThemeController extends AbstractController
{
    #[Route('/', name: 'app_theme_index', methods: ['GET'])]
    public function index(ThemeRepository $themeRepository): Response
    {
        return $this->render('theme/index.html.twig', [
            'themes' => $themeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_theme_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ThemeRepository $themeRepository, SluggerInterface $slugger, UtilisateurRepository $user): Response
    {
        $theme = new Theme();
        $form = $this->createForm(ThemeType::class, $theme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $utilisateur = $user->findOneByMail($this->getUser()->getUserIdentifier());
            $theme->setUtilisateur($utilisateur);
            /** @var UploadedFile $photoFile */
            $photoFile = $form->get('photo')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($photoFile) {
                $originalFilename = pathinfo($photoFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$photoFile->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $photoFile->move(
                        $this->getParameter('photos_theme_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                var_dump($newFilename);
                $theme->setPhoto($newFilename);
               }
            $themeRepository->add($theme);
            return $this->redirectToRoute('app_theme_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('theme/new.html.twig', [
            'theme' => $theme,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_theme_show', methods: ['GET', 'POST'])]
    public function show(Theme $theme, MessageRepository $messageRepository, Request $request, UtilisateurRepository $user): Response
    {
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $utilisateur = $user->findOneByMail($this->getUser()->getUserIdentifier());
            $message->setTheme($theme);
            $message->setUtilisateur($utilisateur);

            $messageRepository->add($message);
            return $this->redirectToRoute('app_theme_show', ['id' => $theme->getId()], Response::HTTP_SEE_OTHER);
        }

        $messages = $messageRepository->findByTheme($theme);
        return $this->renderForm('theme/show.html.twig', [
            'theme' => $theme,
            'messages' => $messages,
            'form' => $form
        ]);
    }

    #[Route('/{id}/edit', name: 'app_theme_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Theme $theme, ThemeRepository $themeRepository): Response
    {
        $form = $this->createForm(ThemeType::class, $theme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $themeRepository->add($theme);
            return $this->redirectToRoute('app_theme_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('theme/edit.html.twig', [
            'theme' => $theme,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_theme_delete', methods: ['POST'])]
    public function delete(Request $request, Theme $theme, ThemeRepository $themeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$theme->getId(), $request->request->get('_token'))) {
            $themeRepository->remove($theme);
        }

        return $this->redirectToRoute('app_theme_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/theme/_delete_form.html.twig
<form method="post" action="{{ path('app_theme_delete', {'id': theme.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ theme.id) }}">
    <p class="buttons">
  <button class="button">
    <span class="icon">
      <i class="fab fa-github"></i>
    </span>
    <span>Suprimer</span>
  </button>
</form>

templates/theme/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Theme{% endblock %}

{% block body %}
    <h1>Edit Theme</h1>

    {{ include('theme/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_theme_index') }}">back to list</a>

    {{ include('theme/_delete_form.html.twig') }}
{% endblock %}

templates/theme/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Theme index{% endblock %}

{% block body %}
   <div class="container has-background-black mb-5" style="opacity: 0.9;">

    <header class="header mt-5">
        <h1 class="title has-color-grey text-shadows is-uppercase is-size-3 pt-3 pl-4 pb-3">
            Forum <span style="margin-left: 57%;"><a href="/theme/new">Ouvrir une discussion</a></span>
        </h1>
    </header>
    <div class="separator"></div>

    <div class="columns is-multiline mt-5 mb-5">
   {% for theme in themes %}
  <div class="column is-3">
    <div class="card has-background-grey">
      <div class="card-image">
        <figure class="image is-4by3">
        {% if theme.photo %}
          <img src="/CSS/IMG/theme/{{theme.photo}}" alt="Placeholder image">
          {% else %}
            <img src="/CSS/IMG/logo.png" alt="Placeholder image">
          {% endif %}
        </figure>
      </div>
      <div class="card-content">

          <p class="title is-3 has-text-centered pb-2">{{theme.titreTheme}}</p>
        <div class="content">

          {{theme.descriptionTheme}}
          <br>
        </div>
        <div class="level ">
          <div class="level-item">
            <div>
              <a href="/theme/{{theme.id}}" class="button">
                <span class="icon has-text-info">
                  <i class="far fa-eye"></i>
                </span>
                <span>Accéder a la discussion</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
</div>

    
{% endblock %}

templates/theme/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<div class="container has-background-black has-text-white mt-5 mb-5" style="opacity: 0.9;">
    <p class="has-text-white">Ajout d'un theme</p>

    {{ include('theme/_form.html.twig') }}

    <a href="{{ path('app_theme_index') }}">back to list</a>
</div>
{% endblock %}

templates/theme/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Theme{% endblock %}

{% block body %}
  <div class="container has-background-black mb-5 pb-5" style="opacity: 0.9;">

    <header class="header mt-5">
        <h1 class="title has-color-grey text-shadows has-text-centered is-uppercase is-size-3 pt-3 pl-4 pb-3">
            Forum - <a>{{theme.titreTheme}}</a>
        </h1>
    </header>
    <div class="separator"></div>

    {% for message in messages %}

   <article class="message ml-5 mr-5">
  <div class="message-header">
    <p class="is-uppercase">{{message.utilisateur.pseudo}} le {{message.createdAt|date("d/m/Y h:i")}}</p>
  </div>
  <div class="message-body">
   <p>{{message.message}}<p>

  
    <form style="margin-left: 80%" method="post" action="{{ path('app_message_delete', {'id': message.id}) }}" onsubmit="return confirm('Souhaitez vous réellement supprimer votre message ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
        <button class="button">
            <span class="icon">
      <i class="fab fa-github"></i>
    </span>
    <span>Supprimer</span>
  </button>
   <a href="/message/{{message.id}}/edit" class="button">
         <span class="icon has-text-info">
             <i class="far fa-eye"></i>
         </span>
        <span>Edition</span>
    </a>
</form>
  </div>
</article>
 {% endfor %}

 {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn" type="submit">{{ button_label|default('Valider') }}</button>
{{ form_end(form) }}

</div>

   
    
{% endblock %}